---
format: revealjs
---

## Today's Agenda {background-image="Images/background-white_house_graphic_v4_muted_text2.png" .center}

```{r}
# background-size="1920px 1080px"
library(tidyverse)
library(readxl)
```

<br>

::: {.r-fit-text}

**I. How serious is the problem of misinformation in the American electorate?**

Policies to Address Misinformation

- Proposal 2: Investing in institutions for "fact-checking"

:::

<br>

::: r-stack
Justin Leinaweaver (Fall 2024)
:::

::: notes
Prep for Class

1. Readings
    - Martin Bisgaard (2019). “How Getting the Facts Right Can Fuel Partisan-Motivated Reasoning.” American Journal of Political Science. 63(4): 824–839.

:::




## For Today {background-image="Images/background-blue_triangles_flipped.png" .center}

<br>

Proposal 2: Investing in institutions for "fact-checking"

1. Bisgaard (2019)

2. ASSIGNMENT - Find us an example of "fact-checking" in the media you think is effective AND find us an example you think isn't effective.

::: notes

Martin Bisgaard (2019). “How Getting the Facts Right Can Fuel Partisan-Motivated Reasoning.” American Journal of Political Science. 63(4): 824–839.

- How might partisans react to fact checking? Rationalizing reality using selective attribution

In Class Introduce Table 1 from: James Druckman and Mary C. McGrath (2019) “The evidence for motivated reasoning in climate change preference formation.” Nature Climate Change 9: 111–119.

- A really interesting article that lays out a bunch of different possible theories of information processing. The Bayesian processing may be confusing but the structure being built may lend itself to really useful theorizing and policy design

Also consider:

Matthew H. Graham and Shikhar Singh (2024). “An Outbreak of Selective Attribution: Partisanship and Blame in the COVID-19 Pandemic.” American Political Science Review.

:::



## For Next Class {background-image="Images/background-blue_triangles_flipped.png" .center}

<br>

Proposal 3: Changing the news consumption habits of American voters/consumers

1. Peterson and Iyengar (2021)

2. ASSIGNMENT - 1) What are the "best" sources of daily news if your goal is to minimize your intake of misinformation? 2) How close do you come to that goal with your normal approach to tracking current events? 3) What would it take to get you to change?

::: notes

:::