---
format: revealjs
---

## Today's Agenda {background-image="Images/background-white_house_graphic_v4_muted_text2.png" .center}

```{r}
# background-size="1920px 1080px"
library(tidyverse)
library(readxl)
```

<br>

::: {.r-fit-text}

**I. How serious is the problem of misinformation in the American electorate?**

Policies to Address Misinformation

- Proposal 3: Changing the news consumption habits of American voters/consumers

:::

<br>

::: r-stack
Justin Leinaweaver (Fall 2024)
:::

::: notes
Prep for Class

1. Readings
    - Erik Peterson and Shanto Iyengar (2021). “Partisan Gaps in Political Information and Information-Seeking Behavior: Motivated Reasoning or Cheerleading?” American Journal of Political Science 65(1): 133–147.

:::




## For Today {background-image="Images/background-blue_triangles_flipped.png" .center}

<br>

Proposal 3: Changing the news consumption habits of American voters/consumers

1. Peterson and Iyengar (2021)

2. ASSIGNMENT - 1) What are the "best" sources of daily news if your goal is to minimize your intake of misinformation? 2) How close do you come to that goal with your normal approach to tracking current events? 3) What would it take to get you to change?

::: notes

Erik Peterson and Shanto Iyengar (2021). “Partisan Gaps in Political Information and Information-Seeking Behavior: Motivated Reasoning or Cheerleading?” American Journal of Political Science 65(1): 133–147.

- Paying for the "right" answers doesn't overcome partisan motivated reasoning
- Incentives help, but not enough BECAUSE of partisan information selection (news searches but only in your partisan media)


:::



## For Next Class {background-image="Images/background-blue_triangles_flipped.png" .center}

<br>

Proposal 4: Reducing misinformation on social media

1. Budak, Nyhan, Rothschild, Thorson & Watts (2024)

2. Find an example of a government policy or a proposal for a new policy from an NGO, politician or thinktank aiming to address the misinformation problem on social media. How do they frame the problem? How do they hope to address it? Is it a good idea? Why or why not?

::: notes

:::