---
format: revealjs
---

## Today's Agenda {background-image="Images/background-white_house_graphic_v4_muted_text2.png" .center}

```{r}
# background-size="1920px 1080px"
library(tidyverse)
library(readxl)
```

<br>

::: {.r-fit-text}

**I. Road testing measures of democracy**

- Revise and resubmit the paper

:::

<br>

::: r-stack
Justin Leinaweaver (Fall 2024)
:::

::: notes
Prep for Class

1. TBD

:::



## Research Paper 1 {background-image="Images/background-white_house_graphic_blue_v2.png" .center}

<br>

Write a report **summarizing and evaluating** the current health of American democracy

- Remember the target audience matters!

<br>

### The Revision

- **Address ALL feedback AND highlight ALL changes**

- **Due: Oct 20th**

::: notes

**Questions on the assignment?**

:::



## For Next Class {background-image="Images/background-blue_triangles_flipped.png" .center}

<br>

::: {.r-fit-text}
**Do we have a misinformation problem?**

1. Vraga and Bode (2020)

2. Li and Wagner (2020)

:::

::: notes

Next class we shift to our final section of the class focused on contemporary threats to American democracy

<br>

Three short readings to help us:

1. Define the concepts, and 

2. Provide us a basic model to clarify our thinking about the problem

<br>

- **Questions on the assignment?**

:::


