---
format: revealjs
---

## Today's Agenda {background-image="Images/background-white_house_graphic_v4_muted_text2.png" .center}

```{r}
# background-size="1920px 1080px"
library(tidyverse)
library(readxl)
```

<br>

::: {.r-fit-text}

**III. The 2024 Election**

- Is it rational to vote?

:::

<br>

::: r-stack
Justin Leinaweaver (Fall 2024)
:::

::: notes
Prep for Class

1. Check Canvas submissions

2. Bring two markers to class

<br>

It's election day!

- *Open google news and search 'election'*

- **How we feeling?!?!?**

:::



## {background-image="Images/12_1-Vote.png" .center}

::: notes

*Split class in half and assign to each side of the debate*

- *It IS rational to vote vs it is NOT rational to vote*

- GROUPS, use the Canvas submissions to build your best argument on the board!

- Go!

<br>

*PRESENT and DISCUSS each*

<br>

SLIDE: Let's see if a formal model of voting can help us answer this question

:::



## When should I vote? {background-image="Images/background-white_house_graphic_blue_v2.png" .center}

<br>

### Alegbra Warm-up

$$8 = 4x$$

$$16 = .5x$$

$$x = .25(100)$$

::: notes

NO TALKING!

- If you can solve these you have the skills necessary to help me flesh out a simple model of voting

- Take a minute and solve these three equations

<br>

(SLIDE)

:::



## When should I vote? {background-image="Images/background-white_house_graphic_blue_v2.png" .center}

<br>

### Alegbra Warm-up

::: columns
::: {.column width="50%"}

$$8 = 4x$$

$$16 = .5x$$

$$x = .25(100)$$

:::
::: {.column width="50%"}

$$x = 2$$

$$x = 32$$

$$x = 25$$

:::
:::

::: notes

**Everybody get these?**

<br>

Let's use some simple math to explore the decision to vote as a formal model.

- Formal models are useful because they require precise thinking and a high clarity for your arguments.

<br>

Today I'll walk you through one particular model by Edlin, Gelman and Kaplan in 2007

- The article is titled "Voting as a Rational Choice: Why and How People Vote to Improve the Well-being of Others"

- SLIDE

:::



## When should I vote? {background-image="Images/background-white_house_graphic_blue_v2.png" .center}

<br>

::: {.incremental}
::: {.r-fit-text}

- Vote if the benefits > costs

- Vote = Benefits - Costs

- &#916;U = B − c

- &#916;U = pB − c

:::
:::

::: notes

We'll start by attacking this with a simple assumption

- REVEAL: We expect an individual to vote when the perceived benefits of voting exceed the costs of voting

<br>

REVEAL: Let's now present this as a complete equation without an inequality

- This presents the idea as the benefits minus the costs
    
- If the result is greater than zero then we expect you to vote
    
<br>

REVEAL: Let's now use symbols for these ideas and root it in the concept of your utility
    
- B = the benefits of voting
    
- c = the costs of voting

- "Utility" is a concept commonly used in economics to represent the total amount of satisfaction you get from doing something or consuming something

- The delta before `U` represents the relative utility of voting

- Put it all together and this says we expect your likelihood to vote increases with the size of this difference

<br>

REVEAL: One more change and we arrive at the basic rational-choice model of voting and political participation (*see Blais 2000 for overview and references*)

- The benefits assume that your preferred candidate wins, but that's not a guarantee.

- So, `p` is the probability that your vote is decisive in the election

- `p` is a probability running from 0 to 100%

<br>

**Refresh my memory, what happens when you multiply a number, the benefits, by a proportion less than one?**

- (They get smaller!)

- So, if your likelihood of being THE decisive vote (e.g. the vote that wins the election) is tiny then your benefits of voting shrink to almost nothing!

<br>

**Questions on the basic model here?**

<br>

Blais, A. 2000. To Vote or Not to Vote: The Merits and Limits of Rational Choice Theory. University of Pittsburgh Press.

:::



## A Basic Rational-choice Model of Voting and Participation {background-image="Images/background-white_house_graphic_blue_v2.png" .center}

::: {.r-fit-text}

$$\Delta U = pB − c$$

:::

::: notes

In sum, the basic rational-choice model of voting and political participation expects your utility of voting to be sensitive to the benefits of voting, the costs of voting and the likelihood that YOUR vote will decide the election

- Let's use this model to identify hypotheses that predict voting behavior

<br>

Expectation 1: The bigger the benefits of voting (`B`) the more likely voting returns a positive utility

- **What characteristics of a state or an election should be associated with larger benefits of voting?**

<br>

1. The more you "like" the candidate and want them to be the leader

2. The bigger the differences between the candidates (ideology, policy promises, temperament, etc)

3. Electoral systems that give us more parties (proportional representation > majoritarian) should increase the likelihood you "like" one of them or the differences between them are large!

<br>

Expectation 2: The smaller the costs of voting (`s`) the more likely voting returns a positive utility

- **What characteristics of a state or an election should be associated with smaller costs of voting?**

<br>

- Policies to reduce the obstacles to voting: postal voting, weekend voting, election day as national holiday, easier ballots to read and use, more assistance for people who need help, same day registration

- Policies to increase the obstacles to voting: strict voter ID, early registration deadlines, long election day lines

<br>

Expectation 3: The greater the likelihood that your vote will be decisive (`p`) the more likely voting returns a positive utility

- **What characteristics of a state or an election should be associated with a larger probability of being decisive?**

<br>

1. The smaller the size of the population the better chance your vote will be the important one!

2. the closer the election is anticipated to be the better chance your vote will be the important one!
    - Tight races should increase turnout.

<br>

**Are we clear on all these?**

- **What do these predictions tell us to expect in our election today?**

<br>

SLIDE: Let's develop this model further
:::



## A Basic Rational-choice Model of Voting and Participation {background-image="Images/background-white_house_graphic_blue_v2.png" .center}

::: {.r-fit-text}

$$\Delta U = pB − c$$

$$B = B_{self} + N B_{soc}$$

:::

::: notes

Traditionally, `B` is understood to refer to direct benefits to you, the voter. 

- This is the assumption of self-interest.

- But maybe this is a too limited view of the benefits imagined by most voters

<br>

Here we are adding a second equation to our model

- You have to solve the second equation to find the value of `B` that you will plug into the first one

- New approach: TWO types of benefit to voting

- B_self are the individual benefits of voting directly to you,  e.g. traditional self-interest
    - Typically very small
    
- B_soc are the benefits to society "as perceived by the person making the decision whether to vote."

<br>

**What do we think are societal benefits of your preferred candidate winning office?**

- **In other words, how big are the societal stakes you believe are tied to your candidate winning?**

- (Leader X will lower taxes, lower taxes makes everybody personally wealthier, more money in the economy means more jobs are created...)

- (Leader Y will increase taxes to pay for job training for the unemployed, better trained workers get better jobs and get off of welfare...)

- (Leader Z will be more respected globally which will translate to better trade deals and more international cooperation on security issues...)

<br>

The `N` here is the population

- In other words, this formula assumes we multiply those societal benefits by the population!

- **How big does this make `B` in the US case?**

- (Huge, even if the societal benefit is tiny.)

<br>

**Is everyone clear on this addition to our model?**

<br>

**Any problems with this version of the model? Be critical!**

- This may WILDLY overestimate the benefits of voting

- Even a TINY value for B_Soc will be a HUGE number if the population is large!

<br>

SLIDE: Let's fix it!

:::



## A Basic Rational-choice Model of Voting and Participation {background-image="Images/background-white_house_graphic_blue_v2.png" .center}

::: {.r-fit-text}

$$\Delta U = pB − c$$

$$B = B_{self} + \alpha N B_{soc}$$

:::

::: notes

The alpha here is a discounting factor, just like the `p` in the top line formula

- We add to the model an assumption that I value the benefits to me more than I value the benefits to the wider society

- When alpha = 0 a voter is selfish (e.g. only values their own benefits and completely discounts the effects on society)

- The more a voter cares about the benefits to society, the higher the value of the alpha

- Most people between 0 and 1.

<br>

**What does this do to the effect of population size on the likelihood of voting?**

- (If you are *selfish* than even a huge population doesn’t change the calculus)

- (If you are more *social* then even a small societal benefit motivates your decision to vote)

<br>

SLIDE: Put it all together

:::



## A Basic Rational-choice Model of Voting and Participation {background-image="Images/background-white_house_graphic_blue_v2.png" .center}

::: {.r-fit-text}

$$\Delta U = p(B_{self} + \alpha N B_{soc}) − c$$

:::

::: notes

Ok, bottom line time

- **When is it rational to vote?**

<br>

Absolutely (for some people)!

- Selfish voters should be very unlikely to turn out IF their odds of being decisive are small

- BUT, the benefits for a socially minded person can be huge even if you aren't the pivotal vote!
    - B_soc grows with N!

<br>

Formal models are kind of cool, no?

:::



## For Next Class {background-image="Images/background-blue_triangles_flipped.png" .center}

<br>

### The election aftermath!

Submit something specific to Canvas (e.g. a "hot take", data, etc) that we can use as a jumping off point to discuss the aftermath of the election!

::: notes

**Questions on the assignment?**

:::