---
format: revealjs
---

## Today's Agenda {background-image="Images/background-white_house_graphic_v4_muted_text2.png" .center}

```{r}
# background-size="1920px 1080px"
library(tidyverse)
library(readxl)
```

<br>

::: {.r-fit-text}

**III. The Final Paper**

- Getting feedback on our op-ed rough drafts

:::
<br>

::: r-stack
Justin Leinaweaver (Fall 2024)
:::

::: notes
Prep for Class

1. Review Canvas submissions

<br>

**So, what have we missed in post-election news?**

- **What's going on in the world?**

:::



## The Final Paper {background-image="Images/background-white_house_graphic_blue_v2.png" .center}

<br>

What is one specific policy we could implement at the local, state or national level that would reduce the levels of misinformation, polarization or affective polarization in American society?

Make your argument in the style of an **op-ed of no more than 800 words (excluding the bibliography)** that you could submit to a newspaper or website interested in thoughtful, well researched analyses of the world we live in.

::: notes

**Questions on the final paper prompt or expected style?**

<br>

Here's the deal, writing an effective op-ed requires iteration

- You only have a few words but you still have to do a number of important things

- Getting an op-ed into great shape takes revision!

<br>

SLIDE: So, let's work on that today!

:::



## {background-image="Images/background-white_house_graphic_blue_v2.png" .center}

### Read and give feedback on all of the drafts

<br>

::: {.incremental}
::: {.r-fit-text}
1. How effective is their news hook (intro)?

2. How clear is their call to action (thesis)? 

3. How credible is their argument (evidence)? 

4. Have they addressed a counter argument (analysis)?
:::
:::

::: notes

Your job today is to read everybody's op-ed in class and give them feedback across four things

- REVEAL x 4

<br>

**Questions on the task?**

- Let's go!

<br>

Next class: Writing Workshop

:::